WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

file = _{ SOI ~ (("lines!" ~ lines) | value) ~ EOI }

value = {
    number
    | list

    | char_lit
    | string_lit
    | array
    | dot_path
    | self_lit
    | string
    | atomic
}


dot_path = { ("." ~ value)* ~ "." }


number = @{ "-"? ~ ASCII_DIGIT+ }
atomic = { "*" ~ number }
list      = { "{" ~ (list_item ~ ("," ~ list_item)* ~ ","?)? ~ "}" }
list_item = { value ~ ":" ~ value }

char_lit   = @{ "'" ~ (("\\" ~ ANY) | (!"'" ~ ANY)) ~ "'" }
string_lit = @{ "\"" ~ (("\\" ~ ANY) | (!"\"" ~ ANY))* ~ "\"" }
string = @{ ASCII_ALPHANUMERIC+ }
array    = { "[" ~ (value ~ ("," ~ value)* ~ ","?)? ~ "]" }
self_lit = @{ "<>" }

set_statement   = { value ~ assign_op ~ value }
assign_op       = { "=" | "<-" | "->" }
lines = { (set_statement | value)* }
